library(shiny)
library(knitr)
library(bslib)
library(ggplot2)
library(plotly)
library(leaflet)
library(nCov2019)
library(lubridate)
library(scales)
library(ggplot2)
library(rgeos)
library(lubridate)
library(tidyr)
library(DT)
library(shinydashboard)
library(dplyr)

get_latest_data <- getFromNamespace("get_latest_data", "nCov2019")
get_global_data <- getFromNamespace("get_global_data", "nCov2019")
get_history_data <- getFromNamespace("get_history_data", "nCov2019")
get_vaccine_data <- getFromNamespace("get_vaccine_data", "nCov2019")
get_therapeutics_data <- getFromNamespace("get_therapeutics_data", "nCov2019")